### PR TITLE
Enhancement: Use --working-dir option when normalizing composer.json

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] uses the `--working-dir` option when invoking `composer normalize`

Related to https://github.com/localheinz/composer-normalize/issues/165.

💁‍♂️ Not sure, will this help?

### CODE REVIEW

**Comment by marcmascort** [comment]
Thanks @localheinz !
We can try this, but not work for supackages.

**Comment by localheinz** [comment]
@marcmascort 

> We can try this, but not work for supackages.

By any chance, can you provide me with a concrete example, so I can try it out myself?

**Comment by marcmascort** [comment]
I created an example at: https://github.com/articstudio/php-bin-example
```
composer install
php ./vendor/bin/phpbin composer:normalize Articstudio/GitTest
```

**Comment by localheinz** [comment]
@marcmascort 

> I created an example at: https://github.com/articstudio/php-bin-example

Appears that the project is private, can you make it public so I can take a look?

**Comment by marcmascort** [comment]
@localheinz 
> Appears that the project is private, can you make it public so I can take a look?

Sorry! Now is public.

**Comment by localheinz** [comment]
@marcmascort 

Can confirm that using the `--working-dir` option does not work when `localheinz/composer-normalize` is not installed in the specified directory.

Will undeprecate!

**Comment by marcmascort** [comment]
Thanks @localheinz !

We also tested it, and our conslucion is the same.

**Pull request closed without merging**
